#!/bin/bash


if [ "$#" -ne 1 ]; then
    echo "usage: $0 <ip or hostname>"
    exit
fi

printf "%-12.12s\t" "$1:"
wget -q -O - http://$1/status | sed -e "s/^.*\"power\"://g" | sed -e "s/\,.*//g"
printf " W\n"

