#!/bin/bash


if [ "$#" -ne 1 ]; then
    echo "usage: $0 <ip or hostname>"
    exit
fi

printf "%-12.12s\t" "$1:"
wget -q -O - http://$1/relay/0 | sed -e "s/^.*\"ison\"://g" | sed -e "s/\,.*//g"
printf "\n"

